### ISSUE TITLE
Need Python 3.9?

### ISSUE THREAD

**Issue by bram98** [spyder-ide/spyder-vim#95]
After installing using pip like in the tutorial, I get the following error message (see below). The last two lines suggest this script is using Python 3.9 syntax. It is nowhere mentioned, that I could find, that this plugin is Python 3.9>. I suggest either indicating a minimum Python version, or patching this syntax so more Python versions are supported.

```
[Traceback (most recent call last):
  File "C:\Users\LINX_Local\anaconda3\envs\bram\Scripts\spyder-script.py", line
10, in <module>
    sys.exit(main())
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder\app\sta
rt.py", line 256, in main
    mainwindow.main(options, args)
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder\app\mai
nwindow.py", line 1823, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder\app\uti
ls.py", line 289, in create_window
    main.setup()
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder\app\mai
nwindow.py", line 731, in setup
    external_plugins = find_external_plugins()
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder\app\fin
d_plugins.py", line 67, in find_external_plugins
    mod = importlib.import_module(entry_point.module_name)
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\importlib\__init__.py", line
 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder_okvim\s
pyder\plugin.py", line 23, in <module>
    from spyder_okvim.spyder.widgets import SpyderOkVimPane, VimWidget
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder_okvim\s
pyder\widgets.py", line 25, in <module>
    from spyder_okvim.executor import (
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder_okvim\e
xecutor\__init__.py", line 5, in <module>
    from .executor_normal import ExecutorNormalCmd
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder_okvim\e
xecutor\executor_normal.py", line 14, in <module>
    from spyder_okvim.executor.executor_base import (
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder_okvim\e
xecutor\executor_base.py", line 8, in <module>
    from spyder_okvim.utils.helper_motion import HelperMotion
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder_okvim\u
tils\helper_motion.py", line 41, in <module>
    class HelperMotion:
  File "C:\Users\LINX_Local\anaconda3\envs\bram\lib\site-packages\spyder_okvim\u
tils\helper_motion.py", line 677, in HelperMotion
    def get_cursor_pos_of_viewport(self) -> tuple[int, int]:
TypeError: 'type' object is not subscriptable](url)
```

**Comment by bram98** [comment]
P.S. after removing all type annotations it now works

**Comment by bram98** [comment]
I commented on the wrong package (okvim) sorry!
